### ISSUE TITLE
D365 Configuration

### ISSUE THREAD

**Issue by emsbarcode** [AlexaCRM/integration-dynamics#17]
Hello,

I installed and activated the plugin but cannot find the location to configure it. The instructions refer to “Admin > Dynamics CRM” but I cannot find this location.

**Comment by georged** [comment]
@emsbarcode 

plugin can be configured using _standard_ configuration links

On the left-hand side in admin area either click **Plugins** then click **Settings** under **Dynamics 365 Integration**, or scroll down if required and click **Dynamics 365** link

**Comment by emsbarcode** [comment]
I don't think I'm seeing the same. I attached an image.


![d365_plugin](https://user-images.githubusercontent.com/32367514/30981267-7cd5deca-a449-11e7-95d3-76feb326c482.jpg)

**Comment by georged** [comment]
@emsbarcode 

that is unusual. Though... hold on... Is your install a multi-site install by any chance? If so then any plugin needs to be installed by a super admin and permission given to activate it on individual sites, afaik. Though unlikely since you were able to activate it... Strange... Caching, perhaps? Try Ctrl-F5 hard refresh.

Actually, try going directly to http://yoursiteurl/wp-admin/admin.php?page=wordpresscrm

**Comment by emsbarcode** [comment]
Just found the issue. There's a not so obvious message telling me the version of PHP I'm running is not compatible. I'll upgrade and try again.

**Comment by emsbarcode** [comment]
It's there now. Sorry to bother you. I"m really excited about this plugin though.

**Comment by georged** [comment]
Thanks for letting us know. We did document compatibility level, not much we can do proactively once the plugin is loaded, unfortunately
