### ISSUE TITLE
CRM Layout not reflected on form

### ISSUE THREAD

**Issue by zargon22** [AlexaCRM/integration-dynamics#23]
i am trying to show same lay out of form as in CRM, i used the caption below. but still the form show as default (Labels on the Left and text fields on the right)

[msdyncrm_form entity="lead" name="Web-Lead" mode="create" captcha="true" message="Thanks!" hide_form="true" default="{firstname:Name}{lastname:=Father}" validation_error="true" enable_layout="true" ]

**Comment by georged** [comment]
@zargon22 

1. What is the form layout in Dynamics? 
2. Have you published the customizations?

Note that in general we'll be deprecating this shortcode in favor of [msdyncrm_twig] shortcode with the {% form %} tag, see https://docs.alexacrm.com/wpcrm/twig/#forms

Thanks

**Comment by zargon22** [comment]
@georged 
1. form is like below.
label text, label text
label text, label text
Label Multi Text

2, customization is published and checked the form display on CRM

3. i will give the twig format a try

**Comment by georged** [comment]
@zargon22 

just following it up to see if you had any luck with twig. If not, we'll investigate further what seems to be  breaking in your layout. We did have some issues in the past with the upgraded forms containing invalid FormXml, I wonder if your issue is similar. Can you tell us if your form was upgraded from the previous versions of Dynamics? If yes, would it be possible to create a Quick Create form with the required layout and try displaying that fresh form?

Thanks
George
