### ISSUE TITLE
Contact form 7

### ISSUE THREAD

**Issue by GordonNishinski** [AlexaCRM/integration-dynamics#9]
Hello, how exactly does the binding of contact form 7 form fields work?

**Comment by georged** [comment]
@GordonNishinski, free version of the plugin does not have cf7 integration. Premium addon (will be released shortly) does have it in place though. Binding is via custom extension of the field tags, e.g. instead of `[email*... ]` you would have something like `[msdyncrm* ... field:emailaddress1]`

HTH
George
